# Generated by Django 5.0.7 on 2024-08-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porfolioform',
            options={'verbose_name': 'Portafolio', 'verbose_name_plural': 'portafolios'},
        ),
        migrations.AlterField(
            model_name='porfolioform',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='porfolioform',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='porfolioform',
            name='subtitle',
            field=models.CharField(max_length=200, verbose_name='Subtitulo'),
        ),
    ]
