# Generated by Django 5.0.7 on 2024-08-01 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0003_alter_porfolioform_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='porfolioform',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='porfolioform',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
