# Generated by Django 5.0.7 on 2024-08-01 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0004_porfolioform_created_porfolioform_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porfolioform',
            options={'ordering': ['-created'], 'verbose_name': 'Portafolio', 'verbose_name_plural': 'portafolios'},
        ),
        migrations.AlterField(
            model_name='porfolioform',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de crecion'),
        ),
        migrations.AlterField(
            model_name='porfolioform',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion'),
        ),
    ]
