# Generated by Django 5.0.7 on 2024-08-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0005_alter_porfolioform_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='porfolioform',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
    ]
